FROM ubuntu
RUN echo '===== Update apt =====' && \
apt update && \
echo '===== Install ssh =====' && \
apt install -y ssh && \
echo '===== Install vim =====' && \
apt install -y vim && \
echo '===== PermitRootLogin in sshd_config =====' && \
echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
EXPOSE 22