FROM ubuntu
RUN echo '===== Update apt =====' && \
apt update && \
echo '===== Install ssh =====' && \
apt install -y ssh && \
echo '===== Install vim =====' && \
apt install -y vim && \
echo '===== Install pip3 =====' && \
apt install -y python3-pip && \
echo '===== Install ansible =====' && \
pip3 install ansible && \
echo '===== Create /etc/ansible dir =====' && \
mkdir /etc/ansible && \
echo '===== Create /etc/ansible/hosts file =====' && \
touch /etc/ansible/hosts && \
echo '===== Update ansible hosts ====='
RUN ["/bin/bash", "-c", "echo -e '[playground]\nans-host' >> /etc/ansible/hosts"]
EXPOSE 22