version: "3.7"

services:
  ans-controller:
    build:
      context: .
      dockerfile: Dockerfile.controller
    image: ans-controller
    container_name: ans-controller
    tty: true
    networks:
      - sshaccess
    ports:
      - "8001:22"
    volumes:
      - ./shared:/tmp/shared
  ans-host:
    build:
      context: .
      dockerfile: Dockerfile.host
    image: ans-host
    container_name: ans-host
    tty: true
    networks:
      - sshaccess
    ports:
      - "8002:22"
    volumes:
      - ./shared:/tmp/shared

networks:
  sshaccess: