---
- hosts: all
  remote_user: ubuntu

  - name: Update apt
    become: true
    apt:
      update_cache: true

  - name: Install unzip
    become: true
    apt:
      name: unzip
      state: present
