---
- hosts: all
  remote_user: ubuntu

  tasks:
  - name: Create downloads directory
    file:
      path: "{{ home_directory }}/downloads"
      state: directory
      mode: '0755'

  - name: Update apt
    become: true
    apt:
      update_cache: true

  - name: Install unzip
    become: true
    apt:
      name: unzip
      state: present

- hosts: slave1
  remote_user: ubuntu

  tasks:
  - name: Download Deno install script if deno binary does not exist
    get_url:
      url: https://deno.land/x/install/install.sh
      dest: "{{ home_directory }}/downloads"
      mode: '0700'

  - name: Check if deno binary exists
    stat:
      path: /home/ubuntu/.deno/bin/deno
    register: deno_binary

  - debug:
      msg: "Deno binary exists: {{ deno_binary.stat.exists }}"

  - name: Install Deno if deno binary does not exist
    shell: "{{ home_directory }}/downloads/install.sh"
    when: not deno_binary.stat.exists

  - name: Create server directory
    file:
      path: "{{ home_directory }}/server"
      state: directory
      mode: '0755'

  - name: Copy hello.ts to server directory
    copy:
      src: templates/hello.ts
      dest: "{{ home_directory }}/server"

  - name: Create hello service
    become: true
    copy:
      src: templates/hello.service
      dest: /etc/systemd/system/hello.service
  
  - name: Ensure hello.service is running
    become: true
    systemd:
      state: started
      name: hello
